---
name: Build and Release Binaries

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Build {{ matrix.target }}
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          toolchain: 1.79.0
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Packaging
        id: packaging
        run: |
          mkdir -p release
          if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            ARCH="amd64"
          elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            ARCH="arm64"
          fi
          # Create a directory structure inside the tarball
          PACKAGE="beegfs_exporter-${{ github.ref_name }}.linux-${ARCH}"
          echo "PACKAGE=${PACKAGE}" >> $GITHUB_OUTPUT
          mkdir -p release/$PACKAGE
          cp target/${{ matrix.target }}/release/beegfs-exporter release/$PACKAGE/beegfs_exporter
          tar -czvf release/${PACKAGE}.tar.gz -C release $PACKAGE

      - name: Upload binaries as build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.packaging.outputs.PACKAGE }}
          path: release/${{ steps.packaging.outputs.PACKAGE }}.tar.gz
