---
name: Release
on:
  pull_request_target:
    types:
      - closed
jobs:
  release:
    if: |
      github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: "Release new version"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Bump version"
        uses: tj-actions/cargo-bump@v3

      - name: "Write cargo.toml"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.base.ref }}
          commit_message: "chore: update version"
          push_options: --force

      - name: "Checkout updated branch"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: "Publish release"
        id: release-publish
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
